config/routes.rb
Gito::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :path => 'users'

  resources :users do
    resources :sheets do
      get   'history',   on: :member
      get   'upload',    on: :member
      get   'pull',      on: :member
      get   'load_data', on: :member
      post  'save_data', on: :member
    end
  end

  root :to => 'high_voltage/pages#show', :id => 'home'
end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  belongs_to :user
  mount_uploader :sheetdata, SheetdataUploader

  attr_accessor :commit
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates :name, presence: true
  validates :name, uniqueness: true, if: -> { self.name.present? }

  has_many :sheets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html  {
          authenticate_user!
        }
        format.js{
          render :partial => "common/not_logined"
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  
  end


  def require_is_admin
    unless (current_user && current_user.admin?)
      redirect_to root_path, :flash => { :error => "no permission" }
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_filter :login_required
  before_action :find_user

  S3_BUCKET = 'gito_user_repo'
  DATA_FILE = 'data.json'

  def index
    @sheets = @user.sheets.load
  end

  def new
    @sheet = @user.sheets.build
  end

  def show
    @sheet = find_sheet
    @load_url = "#{@sheet.id}/load_data"
    @save_url = "#{@sheet.id}/save_data"
    load_local_data
  end

  def create
    @sheet = @user.sheets.new(sheet_name)

    if @sheet.save
      redirect_to user_sheets_path
      create_local_repo
    else
      render :new
    end
  end

  def edit
    @sheet = find_sheet
  end

  def update
    @sheet = find_sheet

    if @sheet.update(sheet_name)
      redirect_to user_sheet_path
    else
      render :edit
    end
  end

  def destroy
    @sheet = find_sheet
    destory_local_tmp_file
    destroy_s3_object
    @sheet.destroy
    redirect_to user_sheets_path
  end

  def upload
    @sheet = find_sheet
    push(find_local_path)
    redirect_to user_sheet_path
  end

  def pull
    @sheet = find_sheet
    update_local_repo
    redirect_to user_sheet_path
  end

  #TODO: for user load image maybe
  def upload_backup
    @sheet = find_sheet
    @uploader = @sheet.sheetdata
    @uploader.success_action_redirect = upload_user_sheet_url
    if params[:key]
      @sheet.update(:path => params[:key])
      redirect_to user_sheet_path
    end
  end

  def load_data
    @sheet = find_sheet
    load_local_data
    data = {"data" => @sheetdata}
    respond_to do |format|
      format.json  { render :json => data }
    end
  end

  def save_data
    if params[:data]
      sheetdata = params[:data]
      respond_to do |format|
        format.json  {
          render :json => {
            result: 'ok',
            location: url_for(:controller => 'sheets', :action => 'show')
          }
        }
      end

      @sheet = find_sheet
      path = find_local_path
      file = "#{path}/#{DATA_FILE}"

      clone_s3 unless File.exist?(file)

      File.open(file, 'w') do |f|
        f.write(JSON.pretty_generate(sheetdata.as_json))
      end

      git = Git::init(path)
      git.add

      message = params[:commit].to_s
      message = message.size > 0 ? message : 'no comment'
      begin
        git.commit_all(message, :author => "#{@user.name} <#{@user.email}>")
      rescue
        Rails.logger.info 'nothing to commit'
      end
    else
      redirect_to user_sheet_path
    end
  end

  def history
    @sheet = find_sheet
    git = Git::init(find_local_path)

    #TODO: this is ugly
    @commits = Array.new
    commits_by_day = Array.new
    this_date = nil
    #TODO: only in a week, more on separation page
    git.log.since('one week ago').each do |c|
      date = c.date.strftime("%m-%d-%y")
      if this_date == date || this_date == nil
        commits_by_day << c
        this_date = date
      else
        @commits << commits_by_day
        commits_by_day = Array.new
        commits_by_day << c
        this_date = date
      end
    end
    @commits << commits_by_day

    @diffs = Array.new
    @commits.flatten.each do |c|
      @diffs << git.diff(c.parent, c).to_s.split(/\n/).drop(4).join("\n") if c.parent
    end
  end


  private

  def find_user
    @user = current_user
  end

  def find_sheet
    @user.sheets.find(params[:id])
  end

  def find_local_path
    path = "#{Rails.root}/tmp/s3/#{@user.id}/#{@sheet.id}"
  end

  def find_data_template_file
    file = "#{Rails.root}/app/assets/data_template/#{DATA_FILE}"
  end

  def find_upload_folder
    folder = "uploads/#{@sheet.id}.git"
  end

  def find_s3_url
    s3_url = "amazon-s3://.jgit@#{S3_BUCKET}/#{find_upload_folder}"
  end

  def sheet_name
    params.require(:sheet).permit(:name)
  end

  def destroy_s3_object
    s3     = AWS::S3.new
    bucket = s3.buckets[S3_BUCKET]
    bucket.objects.with_prefix(find_upload_folder).delete_all
  end

  def destory_local_tmp_file
    FileUtils.remove_entry(find_local_path, :force => true)
  end

  def push(local_repo_path)
    push = "#{Rails.root}/bin/jgit --git-dir=#{local_repo_path}/.git push"
    IO.popen(push) { |result| Rails.logger.info result.gets }
  end

  def create_local_repo
    path = find_local_path
    file = "#{path}/#{DATA_FILE}"
    FileUtils.mkdir_p(path)
    FileUtils.copy(find_data_template_file, file)
    git = Git::init(path)
    git.add
    message = 'first commit'
    git.commit_all(message, :author => "#{@user.name} <#{@user.email}>")
    remote = git.add_remote("origin", find_s3_url)
    push(path)
  end

  def update_local_repo
    path = find_local_path
    fetch = "#{Rails.root}/bin/jgit --git-dir=#{path}/.git fetch"
    IO.popen(fetch) { |result| Rails.logger.info result.gets }
    # TODO: do merge if any result then
    git = Git::init(path)
    git.merge('origin/master')
  end

  def clone_s3
    clone = "#{Rails.root}/bin/jgit clone #{find_s3_url} #{find_local_path}"
    IO.popen(clone) { |result| Rails.logger.info result.gets }
  end

  def sheet_data_convert(json_hash)
    data = []
    json_hash.each do |key, value|
      data[key.to_i] = value
    end
    return data
  end

  def load_local_data
    file = "#{find_local_path}/#{DATA_FILE}"
    clone_s3 unless File.exist?(file)
    @sheetdata = sheet_data_convert(
      JSON.parse(
        File.read(file)
      )
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2013 <%= Setting.app_name %> All rights reserved.</p>
</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top ">
  <div class="container">
    <div class="navbar-header">
      <a class="button navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to(Setting.app_name, Setting.domain , :class => "navbar-brand" )%>
    </div>
    <div class="navbar-collapse">
      <%= render :partial => "common/user_nav"%>
      <%= render_list :class => "nav navbar-nav pull-right" do |li|
        if not current_user.blank?
          li << link_to("All Sheets", user_sheets_path(current_user))
        end
      end %>  
    </div>
  </div>
  <%= yield :submenu %>
</div>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
	window.location = "/users/sign_in";
}

app/views/common/_search_form.html.erb
<%= form_tag "/search", :class => "navbar-form navbar-left", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav nav-pills pull-right">
  <% if current_user %>    
    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>

      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout", destroy_user_session_path, :method => :delete )
      end %>
    </li>
  <% else %>
    <li> <%= link_to( "Sign Up", new_user_registration_path, :class => "gray-color") %> </li>
    <li> <%= link_to( "Login",   new_user_session_path,      :class => "gray-color") %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render_page_title_tag %>
    <%= render_page_description_meta_tag %>
    <%= render_page_keywords_meta_tag %>
    <%= render_page_image_link_tag %>
    <%= csrf_meta_tag %>
    
    <%= stylesheet_link_tag "application" %>
    
    <%= yield :stylesheets %>
    
    <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
    <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
    <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>
  </head>

  <%= render_body_tag %>
    <%= render :partial => "common/menu" %>

    <div class="container">
      <%= notice_message %>
        <div class="content">
          <div class="row">
            <%= yield %>
            <%= yield (:sidebar) %>
          </div> 
        </div>
        <%= render :partial => "common/footer" %>    
    </div>
  
    <%= render :partial => "common/bootstrap_modal" %>    
    <%= render :partial => "common/facebook_js" %>
    <%= render :partial => "common/google_analytics" %>
   
    <%= javascript_include_tag "application" %>
  
    <%= yield :javascripts %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="introduction" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#introduction" data-slide-to="0" class="active"></li>
    <li data-target="#introduction" data-slide-to="1"></li>
    <li data-target="#introduction" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <div class="center_image">
        <%= image_tag("introduction1.png", :alt => "First slide") %>
      </div>
      <div class="container">
        <div class="carousel-caption">
          <h1>Manage Your Orders.</h1>
          <p>you need a better platform between you and your partners</p>
          <%= if current_user.blank?
                link_to( "Sign up today" ,new_user_registration_path, :class => "btn btn-large btn-primary")
          end %>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="center_image">
        <%= image_tag("introduction2.png", :alt => "Second slide") %>
      </div>
      <div class="container">
        <div class="carousel-caption">
          <h1>Track Your Change.</h1>
          <p>All those painful changes are well tracked.</p>
          <%= if current_user.blank?
                link_to( "Sign up today" ,new_user_registration_path, :class => "btn btn-large btn-primary")
          end %>
        </div>
      </div>
    </div>
    <div class="item">
      <div class="center_image">
        <%= image_tag("introduction3.png", :alt => "Third slide") %>
      </div>
      <div class="container">
        <div class="carousel-caption">
          <h1>Save Your Coffee Hours.</h1>
          <p>Spin up cycle time from injuiries, orders to shippments.</p>
          <%= if current_user.blank?
                link_to( "Sign up today" ,new_user_registration_path, :class => "btn btn-large btn-primary")
          end %>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#introduction" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#introduction" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

app/views/sheets/_showhistory_js.erb
<script>
$(document).ready(function() {
  function bindButton() {
    <% @commits.each do |commit_by_date| %>
      <% commit_by_date.each do |c| %>
        $('body').on('click', <%= raw "\'a[name=#{c.sha}]\'" %>, function (e) {
          e.stopPropagation();
          e.preventDefault();
          <%= raw "$(\'\##{c.sha}\').bPopup();" %>
        });
      <% end %>
    <% end%>
  };
  bindButton();
});
</script>

app/views/sheets/_showtable_js.erb
<script>
$(document).ready(function() {
  var data = <%= raw @sheetdata.to_json %>;
  var dataTable = $("#dataTable");
  
  dataTable.handsontable({
    data: data,
    startRows: 6,
    startCols: 8,
    rowHeaders: true,
    colHeaders: true,
    manualColumnResize: true,
    contextMenu: true,
    //currentRowClassName: 'currentRow',
    //currentColClassName: 'currentCol',
    persistentState: true,
  });
  
  $('#search_field').on('keyup', function (event) {
    var value = ('' + this.value).toLowerCase(), row, col, r_len, c_len, td;
  
    if (value) {
      for (row = 0, r_len = data.length; row < r_len; row++) {
        for (col = 0, c_len = data[row].length; col < c_len; col++) {
          td = dataTable.handsontable('getCell', row, col);

          if (('' + data[row][col]).toLowerCase().indexOf(value) > -1) {
            td.className = 'pass'
          }
          else {
            td.className = '';
          }
        }
      }
    }
  });

  var $parent = dataTable.parent();

  $parent.find('button[name=undo]').click(function () {
    dataTable.handsontable('undo');
  });

  $parent.find('button[name=redo]').click(function () {
    dataTable.handsontable('redo');
  });

  $parent.find('button[name=load]').click(function () {
    $.ajax({
      url: <%= raw @load_url.to_json %>,
      dataType: 'json',
      type: 'GET',
      success: function (res) {
        dataTable.data('handsontable').loadData(res.data);
        console.log('Data loaded');
      },
      error: function () {
        console.log('Load error. This url is not accessable.');
      }
    });
  });

  $parent.find('button[name=save]').click(function () {
    $.ajax({
      url: <%= raw @save_url.to_json %>,
      data: {"data": dataTable.data('handsontable').getData(),
             "commit": $("#commit").val()},
      dataType: 'json',
      type: 'POST',
      success: function (res) {
        if (res.result === 'ok') {
          console.log('Data saved');
          window.location.href = res.location;
        }
        else {
          console.log('Save error.');
        }
      },
      error: function (xhr, status, error) {
        console.log('Save error. This url is not accessable.');
      }
    });
    $(this).hide();
    $(this).after('<button class="btn btn-disable btn-block" title="save data" data-disable-with="Submiting..." />');
  });

  function bindButton() {
    $('body').on('click', 'button[name=dump]', function () {
      var dump = $(this).data('dump');
      var $container = $(dump);
      console.log('data of ' + dump, $container.handsontable('getData'));
    });

    $('body').on('click', 'button[name=mypopup]', function (e) {
      e.preventDefault();
      $('#hide_save').bPopup();
    });
  }
  bindButton();
});
</script>

app/views/sheets/edit.html.erb
<div class="span12">
  <h3> Rename this table </h3>
  <%= simple_form_for [@user, @sheet] do |f| %>
    <%= f.input :name, :hint => "no whitespace allowed", :input_html => { :class => "input-lg"} %>
    <div class="form-actions">
      <%= f.submit "Submit", :data => {:disable_with => 'Submiting...'}, :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/sheets/history.html.erb
<div class="page-header">
  <h3>
    <%= link_to('All', user_sheets_path(@sheet.user, @sheet))%> /
    <%= link_to(@sheet.name, user_sheet_path(@sheet.user, @sheet)) %> / history
  </h3>
</div>

<%= javascript_include_tag "application" %>
<%= render :partial => "showhistory_js" %>

<div class="row">
  <% @commits.each do |commit_by_date| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> <%= commit_by_date[0].date.strftime("%d %b %Y") %> </h3>
    </div>
    <div class="panel-body">
    <% commit_by_date.each do |commit| %>
    <ul class="list-group">
      <%= link_to '#', :class => "list-group-item", :name => "#{commit.sha}" do %>
        <%= holder_tag '40x40', 'user', 'industrial', :class => "pull-left margin_r_10" %>
        <h4 class="list-group-item-heading"> <%= commit.message.split(/\n/)[0] %> </h4>
        <p class="list-group-item-text">
          <%= "#{commit.author.name} authored on #{commit.date}" %>
        </p>
      <% end %>
    </ul>
    <div id=<%= raw "\"#{commit.sha}\"" %> class="hide_commit">
      <a class="b-close"> x </a>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h2 class="panel-title"> show this commit full log here </h2>
        </div>
        <div class="panel-body height500">
          <p> <%= simple_format @diffs.shift %> </p>
        </div>
      </div>
    </div>
    <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/sheets/image_upload.html.erb
  <%= direct_upload_form_for @uploader do |f| %>
    <%= f.file_field :sheetdata %>
    <%= f.submit "Upload", :class => "btn btn-mini btn-primary" %>
  <% end %>

app/views/sheets/index.html.erb
<div class="span12">
  <div class="sheet pull-right">
    <%= link_to("New Sheet", new_user_sheet_path(@user) , :class => "btn btn-mini btn-primary")%>
    &nbsp;
  </div>
  <h3> <%= @user.email %> </h3>
  <p> <%= "Total #{@sheets.size} sheets" %> </p>
  <table class="table">
    <tbody>
      <% @sheets.each do |sheet| %>
        <tr>
          <td> <%= link_to(sheet.name, user_sheet_path(sheet.user, sheet)) %> </td>
          <td> 
            <%= link_to("Rename", edit_user_sheet_path(sheet.user, sheet),
              :class => "btn btnbtn-mini btn-primary") %>
            <%= link_to("Delete", user_sheet_path(sheet.user, sheet),
              :class   => "btn btnbtn-mini btn-warning",
              :method  => :delete,
              :data    => { :confirm => "Areyousure?" }) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sheets/new.html.erb
<div class="span12">
  <h3> Give your table a new name </h3>
  <%= simple_form_for [@user, @sheet] do |f| %>
    <%= f.input :name, :hint => "no whitespace allowed", :input_html => { :class => "input-lg"} %>
    <div class="form-actions">
      <%= f.submit "Submit", :data => {:disable_with => 'Submiting...'}, :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/sheets/show.html.erb
<div class="span12">
  <div class="sheet pull-right">
    <%= link_to("New Sheet", new_user_sheet_path(@user) , :class => "btn btn-mini btn-primary")%>
    &nbsp;
  </div>
  <h3>
      <%= link_to('All', user_sheets_path(@sheet.user, @sheet)) %> / <%= @sheet.name %>
  </h3>
  <div class="span12">
    <pre> <%= @sheet.name %> </pre>
      <div>
        <%= link_to("Rename", edit_user_sheet_path(@sheet.user, @sheet),
          :class => "btn btn-mini btn-primary") %>
        <%= link_to("Delete", user_sheet_path(@sheet.user, @sheet),
          :class   => "btn btn-mini btn-warning",
          :method  => :delete,
          :data    => { :confirm => "Areyousure?" }) %>
      </div>
  </div>

  <h3> This is your latest table </h3>

  <%= javascript_include_tag "application" %>

  <input id="search_field" type="text" placeholder="Search"> </input>
  <button name="undo" class="btn btn-warning"> Undo </button>
  <button name="redo" class="btn btn-info"> Redo </button>
  <div id="dataTable", class="handsontable margin10"> </div>

  <%= render :partial => "showtable_js" %>

  <button name="dump" data-dump="#dataTable" class="btn btn-mini btn-info" title="Prints data to Firebug/Chrome Dev Tools">
    Dump data to console
  </button>

  <button name="load" class="btn btn-mini btn-primary" title="load data">
    Load
  </button>

  <%= link_to("Push", upload_user_sheet_path(@sheet.user, @sheet),
              :class => "btn btn-mini btn-primary", :title => "upload data") %>
  <%= link_to("Pull", pull_user_sheet_path(@sheet.user, @sheet),
              :class => "btn btn-mini btn-primary", :title => "update data") %>

  <button name="mypopup" class="btn btn-mini btn-primary" title="save data by popup">
    Save up
  </button>

  <div id="hide_save" class="hide_save">
    <a class="b-close">x</a>
    <h3> Leave comment before you save </h3>
    <%= simple_form_for [@user, @sheet] do |f| %>
      <%= f.text_area :commit, :id => "commit", :rows => 5, :class => "input-lg full-textarea" %>
      <div class="form-actions margin_t_10">
        <button name="save" class="btn btn-primary btn-block" title="save data" data-disable-with="Submiting...">
          Submit
        </button>
      </div>
    <% end %>
  </div>

  <%= link_to("History", history_user_sheet_path(@sheet.user, @sheet),
              :class => "btn btn-mini btn-success", :title => "check history") %>
</div>

app/views/sheets/upload.html.erb
  <%= direct_upload_form_for @uploader do |f| %>
    <%= f.file_field :sheetdata %>
    <%= f.submit "Upload", :class => "btn btn-mini btn-primary" %>
  <% end %>

app/views/spreadsheets/edit.html.erb
<div class="span12">
    <%= simple_form_for [@user, @spreadsheet] do |f| %>
    <%= f.input :content, :input_html => { :class => "input-xxlarge"} %>
    <div class="form-actions">
      <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/spreadsheets/new.html.erb
<div class="span12">
  <%= simple_form_for [@user, @spreadsheet] do |f| %>
    <%= f.input :content, :input_html => { :class => "input-xxlarge"} %>
    <div class="form-actions">
      <%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>